### ISSUE TITLE
Specifying future deadlines.

### ISSUE THREAD

**Issue by Lourenzutti** [UBC-DSCI/rudaux#106]
As discussed on slack, a nice feature for rudaux would be to allow us to specify a deadline after a student deadline has already passed.

Rudaux would check for each student if deadline is in the future, clear out any intermediate stuff if it exists
and then after deadline is passed, do the grading.

**Comment by trevorcampbell** [comment]
I will aim to do this as part of the big shift to Prefect in #95 !

**Comment by trevorcampbell** [comment]
If we do #137 properly, that should handle this. Basically when we run a flow, we check if source info is newer than dest info, and then rerun flow if so. So in this case we'd check if the student's submission was newer (i.e. from a more recent snapshot).
