### ISSUE TITLE
Monitoring the grading

### ISSUE THREAD

**Issue by Lourenzutti** [UBC-DSCI/rudaux#107]
It would be nice for rudaux to allow the instructor to log in with their password and graders username to monitor the grading (and checking for test errors). 

@trevorcampbell first thoughts indicate that this is a small change in `dictauth`.

**Comment by trevorcampbell** [comment]
This has been handled in #40146f026451f038972ddb252e40f4b55d9976a1 as part of the big change to use Prefect flows per #95 . 

I'll leave this issue open though until we update the documentation / README to tell people how to use the new functionality.
