### ISSUE TITLE
tests folder doesn't exists

### ISSUE THREAD

**Issue by dotto95** [UBC-DSCI/rudaux#110]
In the tutorial (https://ubc-dsci.github.io/rudaux/content/infrastructure/setup-rudaux.html) point 3:
"Compile the rudaux config template in rudaux / tests / rudaux_template_config.py and put it in your home folder and rename it rudaux / tests / rudaux_config.py"

This path no longer exists. How could I go on?

Thank you so much :)

**Comment by trevorcampbell** [comment]
@dotto95 the template config is now in the `rudaux/scripts/rudaux_config_template.py` file

Just FYI: this repo is still very much in early stages -- it won't be easy to use!

**Comment by dotto95** [comment]
Thank you :) Solved!
