### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by dotto95** [UBC-DSCI/rudaux#111]
Hello everybody ;)
I have finished my installation, but when I add the external tool "Jupyterhub" to Canvas LMS (with generated keys) I get the following error 

> 405 method not allowed

 (please, see the screenshot). It seems that it does not recognize to authenticate:

![image](https://user-images.githubusercontent.com/80043308/110090397-89c73680-7d97-11eb-8537-ae7d8b98c6d9.png)

Settings of external app:

![image](https://user-images.githubusercontent.com/80043308/110091887-4077e680-7d99-11eb-82cf-56d6738e189a.png)

That is my jupyterhub_config (Student server):
```

import os
import sys

from subprocess import check_call

def create_fs_hook(spawner):
      username = spawner.user.name
      callysto_user = 'jupyter'
      course = 'dsci100'
      check_call(['/srv/jupyterhub/zfs_homedir.sh', course, username, callysto_user])

c.Spawner.pre_spawn_hook = create_fs_hook

c.JupyterHub.admin_access = False
c.JupyterHub.base_url = '/jupyter'
c.JupyterHub.confirm_no_ssl = True
c.JupyterHub.hub_ip = '172.17.0.1'
c.JupyterHub.ip = '127.0.0.1'
c.JupyterHub.services = [
    {
        'name': 'idle-culler',
        'admin': True,
        'command': [
            sys.executable,
            '-m', 'jupyterhub_idle_culler',
            '--timeout=10800'
        ]
    }
]



c.JupyterHub.spawner_class = 'dockerspawner.DockerSpawner'
c.DockerSpawner.extra_host_config = {'mem_limit': '2g', 'memswap_limit': '2g', 'cpu_period': 100000, 'cpu_quota': 100000, 'ulimits': [{'name': 'core', 'hard': 0}] }
c.DockerSpawner.remove_containers = True
c.DockerSpawner.use_internal_ip = True
c.DockerSpawner.host_ip = '0.0.0.0'
c.DockerSpawner.image = 'ubcdsci/r-dsci-100:latest'
c.DockerSpawner.volumes = {'/tank/home/dsci100/{username}': '/home/jupyter'}

c.JupyterHub.authenticator_class = 'ltiauthenticator.LTIAuthenticator'
c.LTIAuthenticator.consumers  = { os.environ['LTI_CLIENT_KEY']: os.environ['LTI_CLIENT_SECRET'] }

```

**Comment by dotto95** [comment]
After some tests, I found that checking the option: "Load This Tool In A New Tab" works but obviously jupyter notebook it is not included in the assignment of the Canvas course.

![image](https://user-images.githubusercontent.com/80043308/110096530-4623fb00-7d9e-11eb-8a2b-04b85ef2f2ae.png)

**Comment by trevorcampbell** [comment]
This sounds like an issue for JHub / LTIAuth / Canvas -- but happy to re-open if there's a problem with Rudaux that needs to be addressed.

NB: we are about to do a version upgrade #95 -- as part of that we will be improving the documentation quite a bit. So hopefully it'll be more clear how to get everything set up after that's done.
