### ISSUE TITLE
Include template config file in GitHub repo or write tool that generates one

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#14]
Now that I am writing a config file from scratch for rudaux using [these docs](https://ubc-dsci.github.io/rudaux-docs/config/#configuring-rudaux) I am learning that it would be really nice to keep a template config file in this repo, or make a tool that generates a boiler-plate one when asked.

**Comment by ttimbers** [comment]
Looks like there is one here: https://ubc-dsci.github.io/rudaux-docs/examples/objects#sample-rudaux_configpy but leads to a 404...

**Comment by ttimbers** [comment]
Ah, ok here: https://github.com/UBC-DSCI/rudaux-docs/blob/master/docs/examples.md#example-rudaux_configpy

So now need to make this a separate file that can be downloaded and fix the link above.

**Comment by trevorcampbell** [comment]
There is an example file in `rudaux/scripts/rudaux_config_template.py` now. Closing.
