### ISSUE TITLE
TODO: Use Canvas File Upload API to upload feedback forms along with grades.

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#16]
@samhinshaw - did you have any thoughts where to start for this? I need to do this now, even if I just do in inside Python for now that is fine. So I am wondering if you identified a part of the Canvas API that would do this?

**Comment by samhinshaw** [comment]
Yes! It seemed like it was a two-step process: https://canvas.instructure.com/doc/api/file.file_uploads.html

@ttimbers

**Comment by ttimbers** [comment]
I think it can't be done with an external tool submission, [here](https://canvas.instructure.com/doc/api/submissions.html#method.submissions_api.create_file) under `submission[file_ids][]` it says "Requires a submission_type of “online_upload”."

**Comment by ttimbers** [comment]
Perhaps we can instead send the feedback files back as attachments using the [Conversations API](https://canvas.instructure.com/doc/api/conversations.html#method.conversations.create)

**Comment by ttimbers** [comment]
To do this, it looks like we need to:

1.  upload files to the sender's “conversation attachments” folder
2. Create a conversation where we attach the file (via `attachment_ids`)

**Comment by ttimbers** [comment]
OK, and there's a trick to it, as there' a bug (hurray!), it's documented here: https://community.canvaslms.com/thread/20969-api-problem-attachments-in-create-conversations

**Comment by samhinshaw** [comment]
Oh, I see—because the file upload API can only be used on submissions, and submissions can only be created via the API for the “online_upload” file type?

As for that bug (needing to supply `[]`), I am fairly certain I ran into the same issue with another API endpoint. Fortunately, Calvin pointed out the fix to me!
