### ISSUE TITLE
Automated Grading

### ISSUE THREAD

**Issue by samhinshaw** [UBC-DSCI/rudaux#2]
- Can we make ZFS snapshots automated?
	- They require superuser permissions
	- This could be fixed by running on root crontab
	- Is it possible to use root crontab from python?
	- Perhaps we can prompt for su access?
- When we initialize the course, we pull down the most recent copy of the instructors repo to get a fresh config file.
	- No GITHUB_PAT is stored, so we are prompted for password. 
	- This won't fly for automated grading. 
	- How should we handle this? 
	- Require a PAT stored on the server? 
	- Should this be run from a system service rather than a cron job?
		- This would solve both of our problems in one go.

**Comment by ianabc** [comment]
For the snapshots, they are (in general) automated through crontab. Theres a role with the snapshot configuration but I haven't added it to the infrastructure yet, I'll try to do that later today. For GitHub, the alternative would be deploy keys, we can generate one with read (or RW) access to the repository as needed and then  have git use ssh and that credential to access the repository when needed.

**Comment by samhinshaw** [comment]
- Recommend automated syncing of instructors repo before and after grading to prevent clashes in gradebook.db
- Theoretically not necessary, as grades will be sent to Canvas
- In the future, will probably want to keep gradebook.db out of version control, and backed up in a more database-friendly way. Could even ignore nbgrader's database altogether and use our own method

- we can store canvas token on grading server without any conflicts? 
	- where is the ideal location for this?
	- currently in `/home/stty2u/.bashrc`

**Comment by samhinshaw** [comment]
Another thought:
- What is the best way to check the system timezone before scheduling a job?

**Comment by samhinshaw** [comment]
TODO: Test nbgrader automated grading call in crontab.

**Comment by ttimbers** [comment]
@ianabc - deploy keys are a great idea to deal with the GITHUB_PAT issue!

>In the future, will probably want to keep gradebook.db out of version control, and backed up in a more database-friendly way. Could even ignore nbgrader's database altogether and use our own method

I really don't know a good tool for this. But I will investigate/talk to others and report back. 

> we can store canvas token on grading server without any conflicts?

I am not sure what you mean by conflicts? Can you please elaborate?

**Comment by samhinshaw** [comment]
- Oh my god, I didn't know about deploy keys! That's amazing, that's exactly what we need.
- The nbgrader [docs](https://nbgrader.readthedocs.io/en/stable/user_guide/philosophy.html#database-of-assignments) and [FAQ](https://nbgrader.readthedocs.io/en/stable/user_guide/faq.html#do-i-have-to-use-sqlite-for-the-nbgrader-database) mention using a different SQL backend. We would need to set up our own Postgres or MySQL database, then point the `CourseDirectory.db_url` configuration option to it. This would give us the option of keeping the database on a different server, and using existing database management/backup tools. 
- I have to be honest I am not sure what I meant by "conflict" either. I authored that comment from my phone, I wonder if there was an autocorrect issue.
	- If we run the automated grading as a service rather than just a cron command, then we can give it access to secure environment variable.
	- However, any script the instructor would run would also need access to these keys for syncing students, creating assignment, etccetera. 
	- For now, I simply put the canvas token into the bashrc file. 
	- However, once we have users logging in from the shib auth we will have to store this in another location. 
	- Part of the reason our grading server is separate is for controlled access anyways, so if we keep this token on the grading server for anyone to use, that should theoretically be okay.
	- Or should each TA have their own token?

**Comment by ttimbers** [comment]
FYI - http://odo.pydata.org/en/latest/ might be the python equivalent of arkdb.

Also, apparently databases also tend to have good tools for dumps. I quickly looked at SQLite and there are some commands to dump from there (also to grab the schema if you wanted to rebuild the db from the dump).

**Comment by ttimbers** [comment]
This is implemented with cron
