### ISSUE TITLE
Docker stacks for JupyterHub

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#27]
- https://github.com/UBC-DSCI/docker-stacks

In particular, this one for the students workspace: https://github.com/UBC-DSCI/docker-stacks/blob/master/r-dsci-100/Dockerfile

**Comment by ttimbers** [comment]
The two we are currently using for the test course are here:
- LTI hub: https://github.com/UBC-STAT/stat-201/blob/master/dockerfiles/r-stat-201/Dockerfile
- Grading hub: https://github.com/UBC-STAT/stat-201/blob/master/dockerfiles/r-stat-201-grading/Dockerfile

Still to do:
- create updated dockerfiles for DSCI 100 for when we move to R 4.0 
- these should live in the public course repo, as I think that is the best workflow now...

**Comment by trevorcampbell** [comment]
This one is quite old and I don't think relevant any more. Closing.
