### ISSUE TITLE
Change littlest jupyterHub authentication to LTI authentication

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#29]
@jyoo980 - let's now try to change littlest jupyterHub authentication to LTI authentication using Canvas. We can use this tool to do this: https://github.com/jupyterhub/ltiauthenticator

**Comment by ttimbers** [comment]
Once you get to generating the secret and key part - let's connect about how to securely share this.

**Comment by jyoo980** [comment]
@ttimbers 

Looks like we're good to close this one?
