### ISSUE TITLE
Install nbgrader on the littlest jupyterHub (that doesn't use Canvas auth)

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#32]
Install nbgrader on the littlest jupyterHub (**that doesn't use Canvas auth**): https://nbgrader.readthedocs.io/en/stable/

**Comment by jyoo980** [comment]
Server running here: http://15.222.4.138/

DM me for details on how to log in.

**Comment by ttimbers** [comment]
this is done
