### ISSUE TITLE
Upgrade Student-facing Jupyterhub to a larger AWS Instance

### ISSUE THREAD

**Issue by jyoo980** [UBC-DSCI/rudaux#34]
**Acceptance Criteria**
- [x] Hub uses DockerSpawner to provision containers for students
- [x] Jupyter labs (not notebooks) should be spawned for students

**Additional resources**
https://github.com/UBC-DSCI/docker-stacks/tree/master/r-dsci-100

**Comment by ttimbers** [comment]
this is done
