### ISSUE TITLE
Have assignment open in Jupyter lab

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#37]
Using Canvas LTI authentication, we can open home in Jupyter lab using this url: http://35.183.155.80/hub/lti/launch

However, when we use nbgitpuller to do the redirect, it doesn't seem to work using this link: http://35.183.155.80/hub/lti/launch?custom_next=/hub/user-redirect/git-pull%3Frepo%3Dhttps%3A%2F%2Fgithub.com%2FUBC-DSCI%2Fdsci-100%26subPath%3Dmaterials%2Fworksheet_01%2Fworksheet_01.ipynb&app=lab

It still just opens it as a Jupyter notebook...

**Comment by trevorcampbell** [comment]
@ttimbers was this ever resolved?

**Comment by ttimbers** [comment]
Yes, the link to do this with our hubs (whose URL's end in `/jupyter/`) is: 

```
https://dsci-100-student.stat.ubc.ca/jupyter/hub/lti/launch?next=%2Fjupyter%2Fhub%2Fuser-redirect%2Fgit-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252FUBC-DSCI%252Fdsci-100%26urlpath%3Dlab%252Ftree%252Fdsci-100%252Fmaterials%252Fworksheet_02%252Fworksheet_02.ipynb%26branch%3Dmaster
```

We should document this somewhere though... There is an issue in that the [nbgitpuller link generator](https://jupyterhub.github.io/nbgitpuller/link.html) doesn't work for our hub well. I opened an issue here describing it, but no traction on the issue yet...

https://github.com/jupyterhub/nbgitpuller/issues/152

**Comment by trevorcampbell** [comment]
Yeah, let's keep this one open for now. We'll either have to add it to our own docs, or if we're lucky and JHub fixes it we can close later.

**Comment by ttimbers** [comment]
They fixed it!!! 🎉 See: https://github.com/jupyterhub/nbgitpuller/pull/172
