### ISSUE TITLE
Use traitlet for config

### ISSUE THREAD

**Issue by daisymzhang** [UBC-DSCI/rudaux#44]
1. for Class Attributes 
2. for type-checking

referencing https://traitlets.readthedocs.io/_/downloads/en/stable/pdf/ ch 1 & 5.

**Comment by daisymzhang** [comment]
parse course url to two parts: base_url + course_id. For example, `https://canvas.instructure.com/courses/2039048/ `would be parsed as `base_url = https://canvas.instructure.com/` and `course_id = 2039048`

**Comment by trevorcampbell** [comment]
No longer relevant.
