### ISSUE TITLE
AWS Snapshots

### ISSUE THREAD

**Issue by hsmohammed** [UBC-DSCI/rudaux#46]
Hi @ttimbers,
I am working on automating the snapshots using AWS Lifecycle policies. what do you suggest for the frequency of taking the snapshots?

**Comment by ttimbers** [comment]
- use cron instead
- want 2 weekly zfs snapshots, one on Wed at 6pm, one on Sat at 6pm. This is something we will eventually to be flexible

**Comment by ttimbers** [comment]
This is the cron job that is currently run on the DSCI 100 server:

```
10 6 * * 0,4 root PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/sbin/zfs-auto-snapshot --quiet --syslog --keep=180 //
```

You will need to install zfs-auto-snapshot and cron first.

**Comment by hsmohammed** [comment]
I am done setting up the snapshots using cron and zfs system. The student server is on the UTC time, so I set it up to take snapshots on 1 am UTC on Saturdays and Wednesdays.

**Comment by ttimbers** [comment]
Can you please record here the notes on how you did this exactly (so we can refer back to them). Thanks for doing this!

**Comment by hsmohammed** [comment]
Sure!

- I installed zfs, zfstools. I didn't need to install cron.
- I logged in to the student server as the "ubuntu" user.
- In the terminal I used the following command
```
crontab -e
```
- That opened a file for me to edit and I inserted the following cron line
```
0 1 * * 3,6 root PATH=/sbin:/bin:/usr/sbin:/usr/bin /usr/sbin/zfs-auto-snapshot --quiet --syslog --keep=180 //
```

**Comment by trevorcampbell** [comment]
Rudaux handles this
