### ISSUE TITLE
Use docker python api for docker commands.

### ISSUE THREAD

**Issue by daisymzhang** [UBC-DSCI/rudaux#48]
https://github.com/docker/docker-py

1. Instead of command line in python with subprocesses, use docker for better error handling. Eventually, we want to collect a list of errors, and then send emails to notify people at the end of each cron job.

2. run a single docker container and run nbgrader's various commends, instead of opening a new docker container, run a nbgrader command, then close the docker container, and repeat.

Relevant legacy code examples:
docker_command = 'docker run --rm -v ' + local_repo_path +':/home/jupyter ubcdsci/r-dsci-grading nbgrader generate_assignment --force ' + anm

docker_command = 'docker run --rm -v ' + local_repo_path_prefix +':/home/jupyter ubcdsci/r-dsci-grading nbgrader autograde --assignment=' + anm + ' --student='+course['student_name_prefix']+stu

docker_command = 'docker run --rm -v ' + local_repo_path_prefix +':/home/jupyter ubcdsci/r-dsci-grading nbgrader generate_feedback --force --assignment=' + anm + ' --student='+course['student_name_prefix']+stu

**Comment by trevorcampbell** [comment]
doing this now
