### ISSUE TITLE
Send useful error message when assignments on dipatch.py and canvas don't match

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#51]
If an instructor removes an assignment from Canvas, but doesn't remove it from dispatch then a useful error message should be logged.

**Comment by trevorcampbell** [comment]
This is already in #50 -- I think while we are doing big initial coding stuff we should collect all these unit test cases in one issue to keep @daisymzhang sane. Once we are happy with an initial version, we can create separate issues for each new one that pops up!
