### ISSUE TITLE
Implement proper logging

### ISSUE THREAD

**Issue by samhinshaw** [UBC-DSCI/rudaux#6]
Use the python logger module instead of print statements to allow for multiple log levels. A warning level would be great for situations such as multiple matches to a search or filter query. 

Then, make sure we're getting good logs for our CLI commands. In fact, consider writing log output for all CLI commands to the instructors repository, alleviating the need to write in a stdout redirect in the cron job.

**Comment by trevorcampbell** [comment]
This is handled by Prefect now.
