### ISSUE TITLE
Deployment Note

### ISSUE THREAD

**Issue by samhinshaw** [UBC-DSCI/rudaux#7]
Rudaux currently requires my fork of nbgrader-0.6.0dev to work properly. This is due to the lack of a `feedback()` call in the nbgrader API. 

I have created [a PR to the nbgrader repo](https://github.com/jupyter/nbgrader/pull/1003), but my tests were not written properly, and therefore the CI is failing. However, the API function still works as expected. 

This fork can be installed with the following command

```sh
pip install git+git://github.com/samhinshaw/nbgrader.git
```

**Comment by ttimbers** [comment]
@samhinshaw - can you please link to the PR so others can help get this PR merged (i.e., work on the tests)?

**Comment by samhinshaw** [comment]
🤦🏻‍♂️ That would be helpful!

https://github.com/jupyter/nbgrader/pull/1003

**Comment by trevorcampbell** [comment]
This was implemented in a different PR upstream.
