### ISSUE TITLE
Package missing from requirements.txt

### ISSUE THREAD

**Issue by ttimbers** [UBC-DSCI/rudaux#8]
When I tried `pip install rudaux` locally (I know it won't run locally, I just wanted to test install) I ran into  this error: `ModuleNotFoundError: No module named 'weir'`

So I think we need to add `weir` to `requirements.txt`

**Comment by samhinshaw** [comment]
Fixed with d3b9b1e94cbd7a05eebb21900c4488ac4a8292ec
